In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   -------- ------------------------------- 2.6/12.4 MB 16.6 MB/s eta 0:00:01
   -------------------- ------------------- 6.3/12.4 MB 15.5 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.4 MB 14.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 15.0 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 14.2 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
arr = np.array ([10,20,30,40,50])

In [5]:
print (arr)
print (type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
arr0 = np.array(24)

In [17]:
print ('0D array is', arr0)
arr0.ndim
arr0.shape

0D array is 24


()

In [18]:
# Create a 1D Array
arr1 = np.array([1,2,3,4])
print ('1D array is', arr1)
arr1.ndim
arr1.shape

1D array is [1 2 3 4]


(4,)

In [43]:
arr2 = np.array([[1,1,1],[1,2,1]])
print ('2D array is\n', arr2)
arr2.ndim
print("original\n", arr2.shape)
arr2_1=arr2.reshape(3,2)
print("After reshape\n",arr2_1.shape)
print ('2D array is\n', arr2_1)

2D array is
 [[1 1 1]
 [1 2 1]]
original
 (2, 3)
After reshape
 (3, 2)
2D array is
 [[1 1]
 [1 1]
 [2 1]]


In [21]:
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print ('3D array is', arr3)
arr3.ndim
arr3.shape
arr3.size

3D array is [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


12

In [22]:
zero_1d = np.zeros(5)
print("ID Zeros",zero_1d)

ID Zeros [0. 0. 0. 0. 0.]


In [23]:
#2D array of zeros
zero_2d = np.zeros((3,4))
print("2D Zeros",zero_2d)

2D Zeros [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
#3D array of zeros
zero_3d = np.zeros((2,3,4))
print("3D Zeros and Shape of 3d",zero_3d,zero_3d.shape )

3D Zeros and Shape of 3d [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] (2, 3, 4)


In [26]:
#With specific datatype
zeros_int =np.zeros((2,3),dtype=int)
print("\n Interger zeros\n", zeros_int)


 Interger zeros
 [[0 0 0]
 [0 0 0]]


In [28]:
zeros_cpx =np.zeros((2,3),dtype=complex)
print("\n Complex zeros\n", zeros_cpx)


 Complex zeros
 [[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [29]:
ones_1d = np.ones(4)
ones_2d = np.ones((2,3))
ones_3d = np.ones((2,2,3))
ones_int8 = np.ones((2,2),dtype=np.int8)
ones_bool = np.ones((3,3),dtype=bool)

print("1D ones", ones_1d)
print("2D ones", ones_2d)
print("3D ones", ones_3d)
print("int ones", ones_int8)
print("bool ones", ones_bool)

1D ones [1. 1. 1. 1.]
2D ones [[1. 1. 1.]
 [1. 1. 1.]]
3D ones [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
int ones [[1 1]
 [1 1]]
bool ones [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [38]:
arr1 = np.arange(10)
print("0 to 9\n", arr1)
arr1.shape


0 to 9
 [0 1 2 3 4 5 6 7 8 9]


(10,)

In [31]:
#with start, stop, step
arr2 = np.arange(5, 15)
print("\n 5 to 14\n", arr2)


 5 to 14
 [ 5  6  7  8  9 10 11 12 13 14]


In [32]:
arr3 = np.arange(0, 20, 3)
print("\n 0 to 19 step 3\n", arr3)


 0 to 19 step 3
 [ 0  3  6  9 12 15 18]


In [33]:
arr4 = np.arange(10, 0, -1)
print("\n 20 to 0 step -1\n", arr4)


 20 to 0 step -1
 [10  9  8  7  6  5  4  3  2  1]


In [34]:
arr5 = np.arange(0, 2.5, 0.5)
print("\n Float range\n", arr5)


 Float range
 [0.  0.5 1.  1.5 2. ]


In [35]:
#reshape to 2D
arr6= np.arange(5, 10)
print(arr6)

[5 6 7 8 9]


In [45]:
#indexing and slicing
arr2_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [46]:
print("Original 4 X 4 array\n", arr2_2d)

Original 4 X 4 array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [47]:
#Get sub matrix (rows 1-2, col 1-3)
print("\n rows 1-2, col 1,3\n", arr2_2d[1:3, 1:4])


 rows 1-2, col 1,3
 [[ 6  7  8]
 [10 11 12]]


In [48]:
print("Get first 2 rows, all columns:\n",arr2_2d[:2,:])

Get first 2 rows, all columns:
 [[1 2 3 4]
 [5 6 7 8]]


In [50]:
print("Get every other row, every other column\n",arr2_2d[::2,::2])

Get every other row, every other column
 [[ 1  3]
 [ 9 11]]


In [53]:
print("Reverse rows and columns\n",arr2_2d[::-1,::-1])

Reverse rows and columns
 [[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [54]:
#Fancy indexing 

fancyArr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

indices = [1, 3, 5, 7]
print("Indices [1, 3, 5, 7]\n ", fancyArr[indices])

Indices [1, 3, 5, 7]
  [20 40 60 80]


In [55]:
indices_repeat = [0, 0, 0, 2, 2, 3, 5, 5]
print("Repeated Indices [0, 0, 0, 2, 2, 3, 5, 5]\n ", fancyArr[indices_repeat])

Repeated Indices [0, 0, 0, 2, 2, 3, 5, 5]
  [10 10 10 30 30 40 60 60]


In [56]:
indices_neg = [0, -1, -2]
print("negativeIndices [0, -1, -2]\n ", fancyArr[indices_neg])

negativeIndices [0, -1, -2]
  [10 80 70]


In [59]:
fancy2Darray = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Original\n",fancy2Darray)
print("Row 0 and 2\n", fancy2Darray[[0,2]])

Original
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row 0 and 2
 [[1 2 3]
 [7 8 9]]


In [60]:
print("Row in reverse order\n", fancy2Darray[[2,1,0]])

Row in reverse order
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [61]:
row=[0,1,2,0]
col=[0,1,2,2]
print("Specific element\n", fancy2Darray[row,col])

Specific element
 [1 5 9 3]
